/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import interact.DataInteraction;
import interact.GUIInteraction;
import interact.Inboxs;
import interact.Stuffs;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DESKTOP-EQP0G7D
 */
public class frmStuff extends javax.swing.JInternalFrame {

    /**
     * Creates new form template
     */
    private ArrayList<entity.Stuff> alDetails = new ArrayList<entity.Stuff>();
    private ArrayList<entity.Inbox> alInDetails = new ArrayList<entity.Inbox>();
    public frmStuff() {
        initComponents();
        alDetails = Stuffs.getAll();
        alInDetails = Inboxs.getAll();
        refresh();
        setWithTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSize = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelTask = new javax.swing.JLabel();
        txtDeadline = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTask = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        labelCategory = new javax.swing.JLabel();
        cboCategory = new javax.swing.JComboBox<>();
        labelSize = new javax.swing.JLabel();
        chkBig = new javax.swing.JRadioButton();
        chkVeryBig = new javax.swing.JRadioButton();
        chkSmall = new javax.swing.JRadioButton();
        labelChange = new javax.swing.JLabel();
        chkName = new javax.swing.JCheckBox();
        chkTime = new javax.swing.JCheckBox();
        btnClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStuff = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCountItem = new javax.swing.JTextField();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1188, 588));
        setMinimumSize(new java.awt.Dimension(1188, 588));
        setPreferredSize(new java.awt.Dimension(1188, 588));

        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("STUFF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(571, 571, 571))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));
        jPanel2.setToolTipText("");
        jPanel2.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 453));

        labelTask.setText("Task");
        labelTask.setEnabled(false);

        txtDeadline.setEnabled(false);

        txtTime.setEnabled(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtTask.setColumns(20);
        txtTask.setLineWrap(true);
        txtTask.setRows(5);
        txtTask.setWrapStyleWord(true);
        txtTask.setEnabled(false);
        jScrollPane2.setViewportView(txtTask);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        labelCategory.setText("Category");
        labelCategory.setEnabled(false);

        cboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dont have" }));
        cboCategory.setEnabled(false);

        labelSize.setText("Size");
        labelSize.setEnabled(false);

        btnGroupSize.add(chkBig);
        chkBig.setText("Big");
        chkBig.setEnabled(false);

        btnGroupSize.add(chkVeryBig);
        chkVeryBig.setText("Very Big");
        chkVeryBig.setEnabled(false);

        btnGroupSize.add(chkSmall);
        chkSmall.setText("Small");
        chkSmall.setEnabled(false);

        labelChange.setText("Change");
        labelChange.setEnabled(false);

        chkName.setText("Name");
        chkName.setEnabled(false);
        chkName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkNameItemStateChanged(evt);
            }
        });

        chkTime.setText("Time");
        chkTime.setEnabled(false);
        chkTime.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkTimeItemStateChanged(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCategory)
                    .addComponent(labelSize)
                    .addComponent(labelChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTime)
                            .addComponent(chkName)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkBig)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkVeryBig))
                            .addComponent(chkSmall))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDeadline, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTime)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTask)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategory)
                    .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSize)
                    .addComponent(chkBig)
                    .addComponent(chkVeryBig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChange)
                    .addComponent(chkName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkTime)
                .addGap(84, 84, 84))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Table"));
        jPanel3.setMaximumSize(new java.awt.Dimension(600, 32767));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 100));

        tableStuff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableStuff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableStuff.setAutoscrolls(false);
        tableStuff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStuffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStuff);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Count & Graphic"));
        jPanel4.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 23));

        jLabel2.setText("STUFF COUNT:");

        txtCountItem.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCountItem, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCountItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        switch (btnAdd.getText()) {
            case "ADD":
                enableTXTAdd();
                resetTXTAdd();
                btnAdd.setText("SAVE");
                break;
            case "SAVE":
                /*
                if (!validate()) {
                return;
                }
                 */
                int countStuff = GUIInteraction.indentityID("select top 1 * from Stuffs order by ID Desc", "ID") + 1;
                String stuffID = "ST" + countStuff;
                entity.Stuff detail = new entity.Stuff();
                detail.setStuffID(stuffID);
                detail.setStuffName(txtTask.getText());
                detail.setStuffTime(txtTime.getText());
                detail.setStuffDeadtime(txtDeadline.getText());
                alDetails.add(detail);
                Stuffs.insertStuff(detail);
                refresh();
                btnAdd.setText("ADD");
                resetTXTAdd();
                diasbleTXTAdd();
                break;
            case "SEND":
                enableTXTSend();
                resetTXTSend();
                btnAdd.setText("OKE");
                break;
            case "OKE":
                /*
                if (!validate()) {
                return;
                }
                 */
                String cateName = cboCategory.getSelectedItem().toString();
                String cateID = DataInteraction.getCode("Categories", "Name", cateName, "ID");
                System.out.println(cateID);
                String size = null;
                if(chkBig.isSelected()){
                    size = "Big";
                }else if(chkSmall.isSelected()){
                    size = "Small";
                }else if(chkVeryBig.isSelected()){
                    size = "Very Big";
                }
                int i = tableStuff.getSelectedRow();
                String stuffIDd = String.valueOf(tableStuff.getValueAt(i, 0));
                int countInbox = GUIInteraction.indentityID("select top 1 * from Inboxs order by ID Desc", "ID") + 1;
                String inboxID = "IB" + countInbox;
                entity.Inbox inboxDetail = new entity.Inbox();
                inboxDetail.setInboxID(inboxID);
                inboxDetail.setInboxName(txtTask.getText());
                inboxDetail.setCategoryID(cateID);
                inboxDetail.setInboxTime(txtTime.getText());
                inboxDetail.setInboxDeadtime(txtDeadline.getText());
                inboxDetail.setSize(size);
                interact.Stuffs.deleteStuff(stuffIDd);
                alDetails.remove(i);
                alInDetails.add(inboxDetail);
                Inboxs.insertInbox(inboxDetail);
                
                refresh();
                btnAdd.setText("ADD");
                resetTXTAdd();
                diasbleTXTAdd();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tableStuffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStuffMouseClicked
        // TODO add your handling code here:
        int i = tableStuff.getSelectedRow();
        txtTask.setText(tableStuff.getValueAt(i, 1).toString());
        txtTime.setText(tableStuff.getValueAt(i, 2).toString());
        txtDeadline.setText(tableStuff.getValueAt(i, 3).toString());
        btnAdd.setText("SEND");
    }//GEN-LAST:event_tableStuffMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        diasbleTXTAdd();
        resetTXTAdd();
        btnAdd.setText("ADD");
    }//GEN-LAST:event_btnClearActionPerformed

    private void chkNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkNameItemStateChanged
        // TODO add your handling code here:
        if (chkName.isSelected()) {
            txtTask.setEnabled(true);
        } else {
            txtTask.setEnabled(false);
        }
        if (chkTime.isSelected()) {
            txtTime.setEnabled(true);
            txtDeadline.setEnabled(true);
        } else {
            txtTime.setEnabled(false);
            txtDeadline.setEnabled(false);
        }
    }//GEN-LAST:event_chkNameItemStateChanged

    private void chkTimeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkTimeItemStateChanged
        // TODO add your handling code here:
        if (chkName.isSelected()) {
            txtTask.setEnabled(true);
        } else {
            txtTask.setEnabled(false);
        }
        if (chkTime.isSelected()) {
            txtTime.setEnabled(true);
            txtDeadline.setEnabled(true);
        } else {
            txtTime.setEnabled(false);
            txtDeadline.setEnabled(false);
        }
    }//GEN-LAST:event_chkTimeItemStateChanged

    private void refresh() {
        tableStuff.setModel(new model.StuffModel(alDetails));
        setWithTable();
        try {
            txtCountItem.setText(String.valueOf(GUIInteraction.countRecord("select * from Stuffs")));
            GUIInteraction.readToCombo("select * from Categories", cboCategory, "Name");
//            GUIInteraction.readToTable("select * from Stuffs", tableStuff);
        } catch (SQLException ex) {
            Logger.getLogger(frmStuff.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void enableTXTAdd() {
        labelTask.setEnabled(true);
        txtTask.setEnabled(true);
        txtTime.setEnabled(true);
        txtDeadline.setEnabled(true);
    }

    private void enableTXTSend() {
        labelCategory.setEnabled(true);
        labelChange.setEnabled(true);
        labelSize.setEnabled(true);
        labelTask.setEnabled(true);

        cboCategory.setEnabled(true);
        chkBig.setEnabled(true);
        chkSmall.setEnabled(true);
        chkVeryBig.setEnabled(true);
        chkTime.setEnabled(true);
        chkName.setEnabled(true);
    }

    private void diasbleTXTAdd() {
        labelTask.setEnabled(false);
        txtTask.setEnabled(false);
        txtTime.setEnabled(false);
        txtDeadline.setEnabled(false);

        diasbleTXTSend();
    }

    private void diasbleTXTSend() {
        labelCategory.setEnabled(false);
        labelChange.setEnabled(false);
        labelSize.setEnabled(false);
        labelTask.setEnabled(false);

        cboCategory.setEnabled(false);
        chkBig.setEnabled(false);
        chkSmall.setEnabled(false);
        chkVeryBig.setEnabled(false);
        chkTime.setEnabled(false);
        chkName.setEnabled(false);
    }

    private void resetTXTAdd() {
        txtTask.setText(null);
        txtTime.setText(null);
        txtDeadline.setText(null);

        resetTXTSend();
    }

    private void resetTXTSend() {
        cboCategory.setSelectedIndex(0);
        chkBig.setSelected(false);
        chkSmall.setSelected(false);
        chkVeryBig.setSelected(false);
        chkTime.setSelected(false);
        chkName.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup btnGroupSize;
    private javax.swing.JComboBox<String> cboCategory;
    private javax.swing.JRadioButton chkBig;
    private javax.swing.JCheckBox chkName;
    private javax.swing.JRadioButton chkSmall;
    private javax.swing.JCheckBox chkTime;
    private javax.swing.JRadioButton chkVeryBig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelChange;
    private javax.swing.JLabel labelSize;
    private javax.swing.JLabel labelTask;
    private javax.swing.JTable tableStuff;
    private javax.swing.JTextField txtCountItem;
    private javax.swing.JTextField txtDeadline;
    private javax.swing.JTextArea txtTask;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void setWithTable() {
        // 
        int max = 565;
        int column0 = 40;
        int column2 = 110;
        int column1 = max - column0 - column2 * 2;
        tableStuff.getColumnModel().getColumn(0).setPreferredWidth(column0);
        tableStuff.getColumnModel().getColumn(1).setPreferredWidth(column1);
        tableStuff.getColumnModel().getColumn(2).setPreferredWidth(column2);
        tableStuff.getColumnModel().getColumn(3).setPreferredWidth(column2);
    }

}
